[package]
name = "kmn-pairs"
version = "0.1.0"
edition = "2024"
description = "A tool to help find assignments of type k-m-n."
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.9.2"
text_io = "0.1.13"

